name: Publish Package to npm
on:
  push:
    tags:
      - "v**"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      id-token: write # to enable use of OIDC for npm provenance
      issues: write # to be able to comment on released issues
      packages: write # to be able to publish a GitHub package
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@gasol'

      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0
          run_install: true

      - run: pnpm run build
      - run: |
          pnpm recursive publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
